export const top: string;
export const topLeft: string;
export const topRight: string;
export const categories: string;
export const categoriesItem: string;
export const categoriesItemLink: string;
export const posts: string;
export const fullWidth: string;
export const fullWidthContainer: string;
